---
# tasks file for idempotent
- name: Downloading terraform_0.11.7_linux_amd64.zip
  get_url:
    url: https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
    dest: /tmp/terraform_0.11.7_linux_amd64.zip
    owner: root
    group: root
    mode: 0644

#- name: Extract terraform
#  command: unzip -o /tmp/terraform_0.11.7_linux_amd64.zip -d /usr/bin chdir=/tmp 

- name: Extract terraform_0.11.7_linux_amd64.zip file 
  unarchive:
    src: /tmp/terraform_0.11.7_linux_amd64.zip
    dest: /tmp/test
